### ISSUE TITLE
mod suggestion

### ISSUE THREAD

**Issue by vertex101** [End-of-Days-Modpack-Team/Vanilla-Enhanced#1]
I was looking at your modpack and was thinking about adding it to my server so me and my friends can play and when looking through the mod list i noticed you had storage drawers and this here is the mod i was wanting to suggest as it would work along side of the storage drawers mod and it also requires no power to use it 

https://minecraft.curseforge.com/projects/simple-storage-network

**Comment by Gbergz** [comment]
Hey, thanks for the suggestion but i won't officially add this to the modpack. But you can add it on your own. (Both server & client required)
